### ISSUE TITLE
Compare with new Scipy implementation

### ISSUE THREAD

**Issue by Multihuntr** [cheind/py-lapsolver#15]
As of v1.4.0 (Dec 2019) [[1]](https://docs.scipy.org/doc/scipy/reference/release.1.4.0.html#scipy-optimize-improvements) [[2]](https://github.com/scipy/scipy/releases/tag/v1.4.0) Scipy released a new implementation for solving the linear assignment problem. 

The release notes under-sell how much of a speed improvement there is. I adapted the python-based tests found in https://github.com/Yay295/AssignmentProblemComparison, to test the speed across versions and found it to be up to 1000x faster than it used to be on random data.

For completeness: here is [my test script](https://gist.github.com/Multihuntr/3e97ed48d726d0029a994a85a25c98ff), and these are my results:
```
                           |   50x50      250x250   1000x1000
--------------------------------------------------------------
scipy v1.3.4               |  0.009084    0.50559    59.3130
scipy v1.4.1               |  0.000101    0.00198     0.0439
```
They [reference a paper in the source code](https://github.com/scipy/scipy/blob/v1.5.1/scipy/optimize/_lsap.py#L65) which implies that this speedup is from a new, effective algorithm, rather than technical implementation improvements. 

I think that either the tests should be re-run on scipy >1.4.0, or the README should make note that the latest scipy implementation is much faster than indicated.

**Comment by jvlmdr** [comment]
Hey, thanks for highlighting this. We updated the figures in commit 2935ababa635e6a066f144b3fa2440d8540877d5. Indeed it makes a huge difference.

Before:
![Before](https://raw.githubusercontent.com/cheind/py-lapsolver/4eff3d110b2efbd658c1abb463c7a0cb8eb7ad77/lapsolver/etc/benchmark-dtype-numpy.float32.png)

After:
![After](https://raw.githubusercontent.com/cheind/py-lapsolver/2935ababa635e6a066f144b3fa2440d8540877d5/lapsolver/etc/benchmark-dtype-numpy.float32.png)

**Comment by jvlmdr** [comment]
We should perhaps add the version numbers to the legend.

**Comment by Multihuntr** [comment]
Oh, my bad. I looked at the "README" last updated. I didn't think about the jpg itself. Sorry about that.

Including version number _would_ ensure that it is always unambiguously correct. 

But it is correct as-is, so I'll close this as an issue.
