### ISSUE TITLE
How can I get Cost of the solution?

### ISSUE THREAD

**Issue by JohnPekl** [cheind/py-lapsolver#16]
I can only get row and column index from this statement `rids, cids = solve_dense(costs).` How can I get the cost for these output row and column indexes?

I think the cost can be obtained by

    `sum=0
     for i in rids:
        sum = sum+costs[i, cids [i]]`

**Comment by jvlmdr** [comment]
That will work. The canonical technique is `costs[rids, cids].sum()`
