### ISSUE TITLE
Wrong results with the example from Readme

### ISSUE THREAD

**Issue by boguszjelinski** [cheind/py-lapsolver#22]
with 3.10.12 (Ubuntu 22.04.1 3.10.12) the first example gives:
0 2
0 2
0 2

**Comment by cheind** [comment]
will test, next week when I have access to a similar system.

**Comment by cheind** [comment]
Could be related to outdated pybind11. Could you re-try with latest on master? I get the desired output with that version

**Comment by boguszjelinski** [comment]
I regained access to VDI now and could retest after having run "pip install pybind11" again, the same result (wrong) with:
pybind11-2.13.6-py3-none-any.whl
So maybe some other library.
