### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by YanielCarreno** [cheind/py-lapsolver#7]
Hi there,

I just wondering if you have tested the package using python 2.7. I got  an error when I am installing it.

Regards;

Yaniel

**Comment by cheind** [comment]
This package only works for python 3.x

YanielCarreno <notifications@github.com> schrieb am Mo., 22. Juli 2019,
12:14:

**Comment by YanielCarreno** [comment]
Hi cheind,

Thanks for your prompt answer.
